theme: jekyll-theme-cayman
permalink: /:categories/:title:output_ext

markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true

plugins:
  - jemoji
