theme: jekyll-theme-cayman
permalink: /:categories/:title:output_ext

google_analytics: 'UA-77412491-1'
google_ad_client: 'ca-pub-4848513853142926'

disqus_username: mkideal

markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true

plugins:
  - jemoji
