baseURL = 'https://gopherd.com/'
languageCode = 'en'
defaultContentLanguage = 'en'
title = 'Gopherd'
theme = 'researcher'
disableKinds = ['taxonomy', 'term', 'RSS']
enableRobotsTXT = true

[params]
  author = 'Gopherd'
  description = 'We are independent developers creating thoughtful utility apps that make everyday tasks simpler.'
  email = 'i@mkideal.com'

[menu]
  [[menu.main]]
    name = 'Home'
    url = '/'
    weight = 1
  [[menu.main]]
    name = 'Privacy Policy'
    url = '/privacy-policy/'
    weight = 2
  [[menu.main]]
    name = 'Terms of Service'
    url = '/terms-of-service/'
    weight = 3
